window.lectureArchive = [
  {
    id: "spring-2026-upcoming",
    year: "2026",
    semester: "Spring",
    date: "March 25, 2026",
    speaker: "Austin Lei",
    title: "Upcoming UMS Lecture",
    topic: "Community",
    location: "Math 508 Cantor Lounge",
    blurb: "A placeholder for the next lecture announcement.",
    description: "This slot keeps the top of the archive ready for the next announced UMS event. Once the title and abstract are finalized, the card can be updated without changing the page structure.",
    visual: "community"
  },
  {
    id: "fall-2025-archive",
    year: "2025",
    semester: "Fall",
    date: "Archive placeholder",
    speaker: "UMS",
    title: "Fall 2025 Archive",
    topic: "Archive",
    location: "To be announced",
    blurb: "Reserved for the Fall 2025 lecture series.",
    description: "The official UMS navigation already treats Fall 2025 as its own term, so the archive page keeps a dedicated slot for it. New lectures can be added here as they are announced.",
    visual: "algebra"
  },
  {
    id: "summer-2025-seminar",
    year: "2025",
    semester: "Summer",
    date: "Summer seminar archive",
    speaker: "UMS",
    title: "Summer 2025 Learning Seminar",
    topic: "Seminar",
    location: "Schedule in progress",
    blurb: "A dedicated summer term for reading-group style programming.",
    description: "Summer UMS terms are often structured differently from the regular lecture semesters. This entry keeps that distinction visible while leaving room for the eventual speaker list and topic sequence.",
    visual: "analysis"
  },
  {
    id: "spring-2025-archive",
    year: "2025",
    semester: "Spring",
    date: "Spring archive placeholder",
    speaker: "UMS",
    title: "Spring 2025 Lecture Archive",
    topic: "Archive",
    location: "Math Building",
    blurb: "A term-level archive entry for Spring 2025.",
    description: "Spring 2025 sits in the official archive between Fall 2024 and Summer 2025. This placeholder keeps the page scalable and makes it clear where the term will live once detailed entries are added.",
    visual: "topology"
  },
  {
    id: "fall-2024-social",
    year: "2024",
    semester: "Fall",
    date: "September 11, 2024",
    speaker: "UMS",
    title: "Introduction to UMS + Social Event",
    topic: "Community",
    location: "Room 520, Math Building",
    blurb: "An opening event focused on community, introductions, and the semester ahead.",
    description: "The Fall 2024 series opened with a social event to introduce the semester, welcome new attendees, and set the tone for the talks that followed.",
    visual: "community"
  },
  {
    id: "fall-2024-kakeya",
    year: "2024",
    semester: "Fall",
    date: "September 18, 2024",
    speaker: "Matthew Hasse-Liu",
    title: "The Finite Field Kakeya Problem",
    topic: "Combinatorics",
    location: "Room 520, Math Building",
    blurb: "A talk about finite-field analogues of a classic geometric problem.",
    description: "This lecture connected incidence geometry and polynomial methods through the finite field Kakeya problem, highlighting why finite-field models can make difficult geometric questions more approachable.",
    visual: "combinatorics"
  },
  {
    id: "fall-2024-langlands",
    year: "2024",
    semester: "Fall",
    date: "September 25, 2024",
    speaker: "Michael Harris",
    title: "What Is the Langlands Program About?",
    topic: "Number Theory",
    location: "Room 520, Math Building",
    blurb: "A broad introduction to one of the major organizing ideas in modern mathematics.",
    description: "The talk framed the Langlands program as a web of relationships across number theory, geometry, representation theory, and harmonic analysis, with an emphasis on big-picture motivation.",
    visual: "number"
  },
  {
    id: "fall-2024-undergraduate-talks",
    year: "2024",
    semester: "Fall",
    date: "October 2, 2024",
    speaker: "Cassidy Kao, Kate Mekechuk, Lisa Faulkner Valiente, Milena Harned, Pranav Konda, Felix Liu, Nikhil Mudumbi, Eric Shao, Tony Xiao",
    title: "Undergraduate Talks",
    topic: "Research Showcase",
    location: "Room 520, Math Building",
    blurb: "A multi-speaker session featuring student research and expository talks.",
    description: "This evening highlighted undergraduate work across topology, Morse theory, Heegaard Floer homology, and quantum error-correcting codes, giving the semester a strong student-led research moment.",
    visual: "topology"
  },
  {
    id: "fall-2024-generating-functions",
    year: "2024",
    semester: "Fall",
    date: "October 9, 2024",
    speaker: "Fan Zhou",
    title: "A Different Way to Count: Enumerative Combinatorics via Power Series",
    topic: "Combinatorics",
    location: "Room 520, Math Building",
    blurb: "Counting problems, power series, and the language of combinatorial species.",
    description: "This talk explored how generating functions and species can translate counting questions into algebraic operations, offering an accessible doorway into enumerative combinatorics.",
    visual: "combinatorics"
  },
  {
    id: "fall-2024-negative-continued-fractions",
    year: "2024",
    semester: "Fall",
    date: "October 23, 2024",
    speaker: "Nicolas Vilches Reyes",
    title: "A Tour on Negative Continued Fractions",
    topic: "Number Theory",
    location: "Room 520, Math Building",
    blurb: "An expository tour linking continued fractions to geometry and singularities.",
    description: "The lecture introduced negative continued fractions as more than a sign change, showing how they connect to cyclic quotient singularities, polygonal decompositions, and open questions in algebraic geometry.",
    visual: "number"
  },
  {
    id: "fall-2024-mean-curvature",
    year: "2024",
    semester: "Fall",
    date: "November 6, 2024",
    speaker: "Raphael Tsiamis",
    title: "The Geometry of Mean Curvature",
    topic: "Geometry",
    location: "Room 520, Math Building",
    blurb: "Minimal surfaces, singularity models, and why curvature matters.",
    description: "This talk introduced mean curvature as a geometric and analytic object, then used it to motivate minimal surfaces, regularity questions, and the behavior of geometric flows.",
    visual: "geometry"
  },
  {
    id: "spring-2024-social",
    year: "2024",
    semester: "Spring",
    date: "January 31, 2024",
    speaker: "UMS",
    title: "Social Event",
    topic: "Community",
    location: "Room 520, Math Building",
    blurb: "A semester kickoff focused on meeting people and easing into the term.",
    description: "Spring 2024 opened with a low-pressure social event, keeping the archive anchored in both intellectual and community-building programming.",
    visual: "community"
  },
  {
    id: "spring-2024-arithmetic-groups",
    year: "2024",
    semester: "Spring",
    date: "February 7, 2024",
    speaker: "Gyujin Oh",
    title: "Arithmetic Groups vs. Mapping Class Groups",
    topic: "Geometry",
    location: "Room 520, Math Building",
    blurb: "A comparison between two important families of groups from different areas.",
    description: "The talk traced parallels between arithmetic groups and mapping class groups, showing how analogies across fields can reveal deeper structural patterns.",
    visual: "geometry"
  },
  {
    id: "spring-2024-spinors-twistors",
    year: "2024",
    semester: "Spring",
    date: "February 14, 2024",
    speaker: "Peter Woit",
    title: "Spinors and Twistors",
    topic: "Mathematical Physics",
    location: "Room 520, Math Building",
    blurb: "A geometric look at spinors as alternatives to ordinary vector-based language.",
    description: "This lecture introduced spinors and twistors as tools for doing geometry in a different language, blending algebraic structure with physical intuition.",
    visual: "analysis"
  },
  {
    id: "summer-2023-intro",
    year: "2023",
    semester: "Summer",
    date: "June 27, 2023",
    speaker: "Zachary Lihn",
    title: "Introduction to Summer UMS",
    topic: "Seminar",
    location: "Zoom",
    blurb: "An opening conversation about the summer seminar and how the group would run.",
    description: "The first Summer 2023 session introduced the reading seminar structure, discussed possible textbooks, and invited attendees to shape the direction of the program.",
    visual: "community"
  },
  {
    id: "summer-2023-linear-algebra",
    year: "2023",
    semester: "Summer",
    date: "July 11, 2023",
    speaker: "Zachary Lihn",
    title: "The Fundamentals of Linear Algebra",
    topic: "Algebra",
    location: "Zoom",
    blurb: "A review of the basic objects and themes that anchor linear algebra.",
    description: "This seminar session covered linear spaces, linear maps, bases, eigenvectors, and decompositions, treating them as the foundation for the rest of the summer's discussions.",
    visual: "algebra"
  },
  {
    id: "spring-2023-hyperplanes",
    year: "2023",
    semester: "Spring",
    date: "February 1, 2023",
    speaker: "Aiden Sagerman and Zachary Lihn",
    title: "Hyperplanes in Abelian Groups and Twisted Signatures",
    topic: "Algebra",
    location: "UMS Spring 2023",
    blurb: "A talk tying finite abelian groups to diagrammatic ideas from category theory.",
    description: "This event connected coordinate hyperplanes in finite abelian groups with tensor categories and string diagrams, giving a bridge from linear algebra to more abstract diagrammatic thinking.",
    visual: "algebra"
  },
  {
    id: "spring-2023-rational-points",
    year: "2023",
    semester: "Spring",
    date: "February 8, 2023",
    speaker: "Akash Sengupta",
    title: "Rational Points and Rational Curves on Algebraic Varieties",
    topic: "Algebraic Geometry",
    location: "UMS Spring 2023",
    blurb: "How geometry influences arithmetic behavior on varieties.",
    description: "The talk explored how geometric structure can shape the existence and distribution of rational points, using rational curves as a guiding theme.",
    visual: "geometry"
  },
  {
    id: "spring-2023-graphs-groups",
    year: "2023",
    semester: "Spring",
    date: "February 15, 2023",
    speaker: "Inbar Klang",
    title: "Using Graphs to Study Groups",
    topic: "Group Theory",
    location: "UMS Spring 2023",
    blurb: "A Cayley-graph-based view of algebra through combinatorial structure.",
    description: "This lecture used Cayley graphs to show how graph-theoretic features can reflect algebraic properties of groups and their generating sets.",
    visual: "combinatorics"
  },
  {
    id: "spring-2023-symplectic",
    year: "2023",
    semester: "Spring",
    date: "March 1, 2023",
    speaker: "Dusa McDuff",
    title: "The Symplectic Embedding Problem and Rational Curves",
    topic: "Symplectic Geometry",
    location: "UMS Spring 2023",
    blurb: "Holomorphic curves as obstructions inside symplectic geometry.",
    description: "The speaker introduced symplectic embeddings and explained how holomorphic curves can encode obstructions, blending intuition with current research themes.",
    visual: "geometry"
  },
  {
    id: "spring-2023-integrable-hierarchies",
    year: "2023",
    semester: "Spring",
    date: "March 8, 2023",
    speaker: "Patrick Lei",
    title: "Algebraic Curves and Integrable Hierarchies",
    topic: "Geometry",
    location: "UMS Spring 2023",
    blurb: "A story linking algebraic curves with infinite-dimensional equations.",
    description: "This lecture surveyed the correspondence between algebraic curves and integrable systems, highlighting why ideas from geometry and mathematical physics fit together so well.",
    visual: "geometry"
  },
  {
    id: "spring-2023-fourier",
    year: "2023",
    semester: "Spring",
    date: "March 29, 2023",
    speaker: "Rahul Ram",
    title: "Probabilistic Ramifications of L^2 Fourier Series",
    topic: "Analysis",
    location: "UMS Spring 2023",
    blurb: "Fourier convergence viewed through probability and stopping-time ideas.",
    description: "The talk drew a line from Carleson's theorem to probabilistic intuition, showing how analytic convergence questions can be illuminated by a gambler's perspective.",
    visual: "analysis"
  },
  {
    id: "spring-2023-symposium",
    year: "2023",
    semester: "Spring",
    date: "April 28, 2023",
    speaker: "Arjun Kudinoor",
    title: "Spring Research Symposium",
    topic: "Research Showcase",
    location: "UMS Spring 2023",
    blurb: "A broad student research event across several mathematical areas.",
    description: "The symposium gathered undergraduate presentations spanning mathematical physics, gauge theory, differential equations, finance, and other topics to showcase the range of student work.",
    visual: "community"
  }
];
